### PR TITLE
M4D taxonomy - moving taxonomy files to charts/files and creating ConfigMaps

### PR DESCRIPTION
**Pull request by eletonia**
This PR moves the taxonomy JSON files to `charts/files` and creates 4 ConfigMaps in total - one each for m4dapplication, m4dmodule, catalog, and policy manager taxonomies

### CODE REVIEW

**Comment by ronenkat** [comment]
@eletonia can you please resolve the conflict for the taxonomy files?

**Comment by eletonia** [comment]
@ronenkat The conflict is because I deleted the entire `config/taxonomy` directory and moved all these files to `charts/files`

**Comment by eletonia** [comment]
@ronenkat @roee88 I fixed the merge conflicts and modified the config maps to write all the json files in each subfolder to the corresponding config map. Let me know if I should change anything else

**Comment by ronenkat** [comment]
@eletonia can you fix the init test that are failing because the taxonomy files have moved.
check pkg/taxonomy, but I think there is another one as well.

**Comment by eletonia** [comment]
@ronenkat @roee88 I combined the 4 config maps into 1 and removed the subfolders in `charts/files/taxonomy`
All the tests are passing now, can we merge?

**Review by ronenkat — APPROVED** [review]

**Pull request merged**
