### PR TITLE
Operate first - making changes to follow operate-first/apps repo

### PR DESCRIPTION
**Pull request by eletonia**
Changes in this PR:

The `filterClusterScoped.py` script now generates directories according the structure in the `operate-first/apps` repo.
It also changes the names of the yaml files to the `kind` name as they do in `operate-first/apps`. 
See https://github.com/operate-first/apps/pull/588/files 
This required modifying the Kustomization files in each directory as well.

### CODE REVIEW

**Comment by roee88** [comment]
Can you please rebase?

**Comment by eletonia** [comment]
@roee88 I rebased it but some taxonomy files are still in this branch. Once #543 is merged, this PR will only have the modified files for operate-first.

**Comment by ronenkat** [comment]
@eletonia can you please re-base? would be good to have the PRs rooted directly from upstream/master rather than on a local modified branch

**Comment by eletonia** [comment]
@ronenkat I pulled from master and now only relevant files are changed. Can we merge?

**Review by ronenkat — APPROVED** [review]

**Pull request merged**
